### ISSUE TITLE
Question: How to use 

### ISSUE THREAD

**Issue by hassenius** [operator-framework/operator-marketplace#306]
I have built a catalog and pushed it to a private registry, but having issues pulling the image. From my reading of the code, this should work:

```
apiVersion: v1
kind: Secret
metadata:
  name: testcatalogkey
  namespace: openshift-marketplace
data:
  .dockerconfigjson: <a valid base64 of my dockerconfigjson>
type: kubernetes.io/dockerconfigjson
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: test-operators
  namespace: openshift-marketplace
spec:
  authorizationToken:
    secretName: testcatalogkey
  displayName: mytestoperators
  sourceType: grpc
  image: someprivate.docker.registry/hktest/catalog-test:0.0.1
```

But when I deploy this and look in the openshift-marketplace namespace, my container is stuck in `ImagePullBackOff` and `......hktest/catalog-test:0.0.1": rpc error: code = Unknown desc = unable to retrieve auth token: invalid username/password: unknown: Authentication is required

Doing a describe on the pod I see no reference to the secret I created.

Is there any guidance on what I'm doing wrong?
