### ISSUE TITLE
Help with updating OperatorSource

### ISSUE THREAD

**Issue by eivantsov** [operator-framework/operator-marketplace#98]
I have created a csv https://github.com/eclipse/che-operator/blob/0.3.0/olm-catalog/cheoperator.0.0.1.csv.yaml which works fine with OLM.

Followed https://github.com/operator-framework/operator-marketplace/blob/master/docs/how-to-upload-artifact.md and pushed an artifact https://quay.io/application/eivantsov/cheoperator?tab=releases

Updated operatorsource.cr.yaml and applied it:

```
apiVersion: "marketplace.redhat.com/v1alpha1"
kind: "OperatorSource"
metadata:
  name: "global-operators"
  namespace: "openshift-marketplace"
spec:
  type: appregistry
  endpoint: "https://quay.io/cnr"
  registryNamespace: "eivantsov"
  displayName: "Marketplace Operators"
  publisher: "Red Hat"
```

Once configured, I see the following error in operator-marketplace log:

```
time="2019-01-23T09:59:33Z" level=error msg="Error \"package [] not found\" getting manifest" name=global-operators targetNamespace=openshift-marketplace type=CatalogSourceConfig
```

At this point I am puzzled - there must be some errors in one of the yamls but I can't figure out which.

**Comment by eivantsov** [comment]
Also, some logs that say, the manifest was found but not stored?

```

time="2019-01-23T13:36:36Z" level=info msg="Downloading from [https://quay.io/cnr ]" name=global-operators namespace=openshift-marketplace type=OperatorSource
  | time="2019-01-23T13:36:38Z" level=info msg="Downloaded 1 manifest(s) from the operator source endpoint" name=global-operators namespace=openshift-marketplace type=OperatorSource
  | time="2019-01-23T13:36:38Z" level=info msg="Successfully stored 0 operator manifest(s)" name=global-operators namespace=openshift-marketplace type=OperatorSource
  | time="2019-01-23T13:36:38Z" level=info msg="Download complete, scheduling for configuration" name=global-operators namespace=openshift-marketplace type=OperatorSource
```

**Comment by awgreene** [comment]
Hello @eivantsov 

The problem you've encountered is within your `operatorBundle` (name changed from `OperatorArtifact`). The `OperatorBundle` needs to include a list of [Packages](https://github.com/awgreene/community-operators/blob/master/community-operators/jaeger/jaeger.package.yaml) to work with OLM.

**Comment by eivantsov** [comment]
@philips thanks. Where should I create this package object? It's not quite clear from existing readme.

**Comment by awgreene** [comment]
@eivantsov The [README](https://github.com/operator-framework/operator-marketplace/blob/master/docs/how-to-upload-artifact.md) mentions that it should be under `data.packages`:
```
data:
  customResourceDefinitions: |-
  clusterServiceVersions: |-
  packages: |-
```

I'll make sure to improve the documentation to better explain this process. BTW, the README we linked in this thread will be removed in a [future PR](https://github.com/operator-framework/operator-marketplace/pull/93), the update to the docs that I provide will be done in the [community-operators](https://github.com/awgreene/community-operators/tree/templates)
